# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Location.create(city: 'Arches National Park', country: 'United States', name: 'Arches National Park, United States')
Location.create(city: 'Big Sur', country: 'United States', name: 'Big Sur, United States')
Location.create(city: 'Bocas Town', country: 'Panama', name: 'Bocas Town, Panama')
Location.create(city: 'Boquete', country: 'Panama', name: 'Boquete, Panama')
Location.create(city: 'Male', country: 'Maldives', name: 'Male, Maldives')
Location.create(city: 'Tamarindo', country: 'Costa Rica', name: 'Tamarindo, Costa Rica')
Location.create(city: 'Acadia National Park', country: 'United States', name: 'Acadia National Park, United States')
Location.create(city: 'Arenal Volcano National Park', country: 'Costa Rica', name: 'Arenal Volcano National Park, Costa Rica')
Location.create(city: 'Austin', country: 'United States', name: 'Austin, United States')
Location.create(city: 'Baa Atoll', country: 'Maldives', name: 'Baa Atoll, Maldives')
Location.create(city: 'Cape Town Central', country: 'South Africa', name: 'Cape Town Central, South Africa')
Location.create(city: 'Da Nang', country: 'Vietnam', name: 'Da Nang, Vietnam')
Location.create(city: 'Hoi An', country: 'Vietnam', name: 'Hoi An, Vietnam')
Location.create(city: 'Hue', country: 'Vietnam', name: 'Hue, Vietnam')
Location.create(city: 'Isla Colon', country: 'Panama', name: 'Isla Colon, Panama')
Location.create(city: 'Kitulgala', country: 'Sri Lanka', name: 'Kitulgala, Sri Lanka')
Location.create(city: 'Koh Rong', country: 'Cambodia', name: 'Koh Rong, Cambodia')
Location.create(city: 'Koh Tao', country: 'Thailand', name: 'Koh Tao, Thailand')
Location.create(city: 'Luang Prabang', country: 'Laos', name: 'Luang Prabang, Laos')
Location.create(city: 'Medellin', country: 'Colombia', name: 'Medellin, Colombia')
Location.create(city: 'Panama City', country: 'Panama', name: 'Panama City, Panama')
Location.create(city: 'San Francisco', country: 'United States', name: 'San Francisco, United States')
Location.create(city: 'Sayaboury', country: 'Laos', name: 'Sayaboury, Laos')
Location.create(city: 'Sukhothai', country: 'Thailand', name: 'Sukhothai, Thailand')
Location.create(city: 'Vang Vieng', country: 'Laos', name: 'Vang Vieng, Laos')
Location.create(city: 'Aberdeen', country: 'United States', name: 'Aberdeen, United States')
Location.create(city: 'Aguas Calientes', country: 'Peru', name: 'Aguas Calientes, Peru')
Location.create(city: 'Alamogordo', country: 'United States', name: 'Alamogordo, United States')
Location.create(city: 'Albuquerque', country: 'United States', name: 'Albuquerque, United States')
Location.create(city: 'Anaheim', country: 'United States', name: 'Anaheim, United States')
Location.create(city: 'Anchorage', country: 'United States', name: 'Anchorage, United States')
Location.create(city: 'Antigua', country: 'Guatemala', name: 'Antigua, Guatemala')
Location.create(city: 'Ao Nang', country: 'Thailand', name: 'Ao Nang, Thailand')
Location.create(city: 'Athens', country: 'United States', name: 'Athens, United States')
Location.create(city: 'Atlanta', country: 'United States', name: 'Atlanta, United States')
Location.create(city: 'Atlantic City', country: 'United States', name: 'Atlantic City, United States')
Location.create(city: 'Ayutthaya', country: 'Thailand', name: 'Ayutthaya, Thailand')
Location.create(city: 'Badlands National Park', country: 'United States', name: 'Badlands National Park, United States')
Location.create(city: 'Baltimore', country: 'United States', name: 'Baltimore, United States')
Location.create(city: 'Bangkok', country: 'Thailand', name: 'Bangkok, Thailand')
Location.create(city: 'Bangor', country: 'United States', name: 'Bangor, United States')
Location.create(city: 'Banlung', country: 'Cambodia', name: 'Banlung, Cambodia')
Location.create(city: 'Bath', country: 'United Kingdom', name: 'Bath, United Kingdom')
Location.create(city: 'Baton Rouge', country: 'United States', name: 'Baton Rouge, United States')
Location.create(city: 'Battambang', country: 'Cambodia', name: 'Battambang, Cambodia')
Location.create(city: 'Bayahibe', country: 'Dominican Republic', name: 'Bayahibe, Dominican Republic')
Location.create(city: 'Bazaruto Island', country: 'Mozambique', name: 'Bazaruto Island, Mozambique')
Location.create(city: 'Bellevue', country: 'United States', name: 'Bellevue, United States')
Location.create(city: 'Bend', country: 'United States', name: 'Bend, United States')
Location.create(city: 'Bennington', country: 'United States', name: 'Bennington, United States')
Location.create(city: 'Beverly Hills', country: 'United States', name: 'Beverly Hills, United States')
Location.create(city: 'Big Pine Key', country: 'United States', name: 'Big Pine Key, United States')
Location.create(city: 'Billings', country: 'United States', name: 'Billings, United States')
Location.create(city: 'Biloxi', country: 'United States', name: 'Biloxi, United States')
Location.create(city: 'Bozeman', country: 'United States', name: 'Bozeman, United States')
Location.create(city: 'Brooklyn', country: 'United States', name: 'Brooklyn, United States')
Location.create(city: 'Bryce', country: 'United States', name: 'Bryce, United States')
Location.create(city: 'Buffalo', country: 'United States', name: 'Buffalo, United States')
Location.create(city: 'Burlington', country: 'United States', name: 'Burlington, United States')
Location.create(city: 'Bushkill', country: 'United States', name: 'Bushkill, United States')
Location.create(city: 'Butte', country: 'United States', name: 'Butte, United States')
Location.create(city: 'Calistoga', country: 'United States', name: 'Calistoga, United States')
Location.create(city: 'Callicoon', country: 'United States', name: 'Callicoon, United States')
Location.create(city: 'Can Tho', country: 'Vietnam', name: 'Can Tho, Vietnam')
Location.create(city: 'Cancun', country: 'Mexico', name: 'Cancun, Mexico')
Location.create(city: 'Canton', country: 'United States', name: 'Canton, United States')
Location.create(city: 'Cape May', country: 'United States', name: 'Cape May, United States')
Location.create(city: 'Capitola', country: 'United States', name: 'Capitola, United States')
Location.create(city: 'Capri', country: 'Italy', name: 'Capri, Italy')
Location.create(city: 'Carlsbad', country: 'United States', name: 'Carlsbad, United States')
Location.create(city: 'Carmel', country: 'United States', name: 'Carmel, United States')
Location.create(city: 'Cartagena', country: 'Colombia', name: 'Cartagena, Colombia')
Location.create(city: 'Cary', country: 'United States', name: 'Cary, United States')
Location.create(city: 'Castellina In Chianti', country: 'Italy', name: 'Castellina In Chianti, Italy')
Location.create(city: 'Cat Ba', country: 'Vietnam', name: 'Cat Ba, Vietnam')
Location.create(city: 'Catskill', country: 'United States', name: 'Catskill, United States')
Location.create(city: 'Caye Caulker', country: 'Belize', name: 'Caye Caulker, Belize')
Location.create(city: 'Chelan', country: 'United States', name: 'Chelan, United States')
Location.create(city: 'Chiang Mai', country: 'Thailand', name: 'Chiang Mai, Thailand')
Location.create(city: 'Chiang Rai', country: 'Thailand', name: 'Chiang Rai, Thailand')
Location.create(city: 'Chicago', country: 'United States', name: 'Chicago, United States')
Location.create(city: 'Coeur dAlene', country: 'United States', name: 'Coeur dAlene, United States')
Location.create(city: 'Cold Spring', country: 'United States', name: 'Cold Spring, United States')
Location.create(city: 'Colombo', country: 'Sri Lanka', name: 'Colombo, Sri Lanka')
Location.create(city: 'Como', country: 'Italy', name: 'Como, Italy')
Location.create(city: 'Crescent City', country: 'United States', name: 'Crescent City, United States')
Location.create(city: 'Culver City', country: 'United States', name: 'Culver City, United States')
Location.create(city: 'Cusco', country: 'Peru', name: 'Cusco, Peru')
Location.create(city: 'Daytona Beach', country: 'United States', name: 'Daytona Beach, United States')
Location.create(city: 'Dominican Republic', country: 'Dominican Republic', name: 'Dominican Republic, Dominican Republic')
Location.create(city: 'Don Khone', country: 'Laos', name: 'Don Khone, Laos')
Location.create(city: 'Dong Hoi', country: 'Vietnam', name: 'Dong Hoi, Vietnam')
Location.create(city: 'Dover', country: 'United States', name: 'Dover, United States')
Location.create(city: 'Elkton', country: 'United States', name: 'Elkton, United States')
Location.create(city: 'Encinitas', country: 'United States', name: 'Encinitas, United States')
Location.create(city: 'Espanola', country: 'United States', name: 'Espanola, United States')
Location.create(city: 'Eugene', country: 'United States', name: 'Eugene, United States')
Location.create(city: 'Fajardo', country: 'United States', name: 'Fajardo, United States')
Location.create(city: 'Falmouth', country: 'Jamaica', name: 'Falmouth, Jamaica')
Location.create(city: 'Farmington', country: 'United States', name: 'Farmington, United States')
Location.create(city: 'Flagler Beach', country: 'United States', name: 'Flagler Beach, United States')
Location.create(city: 'Florence', country: 'Italy', name: 'Florence, Italy')
Location.create(city: 'Flushing', country: 'United States', name: 'Flushing, United States')
Location.create(city: 'Forks', country: 'United States', name: 'Forks, United States')
Location.create(city: 'Fort Lauderdale', country: 'United States', name: 'Fort Lauderdale, United States')
Location.create(city: 'Fort Stockton', country: 'United States', name: 'Fort Stockton, United States')
Location.create(city: 'Galle', country: 'Sri Lanka', name: 'Galle, Sri Lanka')
Location.create(city: 'Grand Canyon National Park', country: 'United States', name: 'Grand Canyon National Park, United States')
Location.create(city: 'Grand Cayman', country: 'United Kingdom', name: 'Grand Cayman, United Kingdom')
Location.create(city: 'Greenport', country: 'United States', name: 'Greenport, United States')
Location.create(city: 'Greve in Chianti', country: 'Italy', name: 'Greve in Chianti, Italy')
Location.create(city: 'Guatemala City', country: 'Guatemala', name: 'Guatemala City, Guatemala')
Location.create(city: 'Halong Bay', country: 'Vietnam', name: 'Halong Bay, Vietnam')
Location.create(city: 'Hammondsport', country: 'United States', name: 'Hammondsport, United States')
Location.create(city: 'Hanoi', country: 'Vietnam', name: 'Hanoi, Vietnam')
Location.create(city: 'Hat Yai', country: 'Thailand', name: 'Hat Yai, Thailand')
Location.create(city: 'Hawley', country: 'United States', name: 'Hawley, United States')
Location.create(city: 'Hermosa Beach', country: 'United States', name: 'Hermosa Beach, United States')
Location.create(city: 'Hershey', country: 'United States', name: 'Hershey, United States')
Location.create(city: 'Hikkaduwa', country: 'Sri Lanka', name: 'Hikkaduwa, Sri Lanka')
Location.create(city: 'Ho Chi Minh City', country: 'Vietnam', name: 'Ho Chi Minh City, Vietnam')
Location.create(city: 'Hoboken', country: 'United States', name: 'Hoboken, United States')
Location.create(city: 'Hongsa', country: 'Laos', name: 'Hongsa, Laos')
Location.create(city: 'Hood River', country: 'United States', name: 'Hood River, United States')
Location.create(city: 'Huay Xai', country: 'Laos', name: 'Huay Xai, Laos')
Location.create(city: 'Hudson', country: 'United States', name: 'Hudson, United States')
Location.create(city: 'Hyannis', country: 'United States', name: 'Hyannis, United States')
Location.create(city: 'Jacksonville', country: 'United States', name: 'Jacksonville, United States')
Location.create(city: 'Jacksonville Beach', country: 'United States', name: 'Jacksonville Beach, United States')
Location.create(city: 'Jamaica', country: 'United States', name: 'Jamaica, United States')
Location.create(city: 'Jersey City', country: 'United States', name: 'Jersey City, United States')
Location.create(city: 'Johannesburg', country: 'South Africa', name: 'Johannesburg, South Africa')
Location.create(city: 'Joliet', country: 'United States', name: 'Joliet, United States')
Location.create(city: 'Juneau', country: 'United States', name: 'Juneau, United States')
Location.create(city: 'Kandy', country: 'Sri Lanka', name: 'Kandy, Sri Lanka')
Location.create(city: 'Keflavik', country: 'Iceland', name: 'Keflavik, Iceland')
Location.create(city: 'Ketchikan', country: 'United States', name: 'Ketchikan, United States')
Location.create(city: 'Key West', country: 'United States', name: 'Key West, United States')
Location.create(city: 'Khao Sok National Park', country: 'Thailand', name: 'Khao Sok National Park, Thailand')
Location.create(city: 'Killington', country: 'United States', name: 'Killington, United States')
Location.create(city: 'Kissimmee', country: 'United States', name: 'Kissimmee, United States')
Location.create(city: 'Ko Lanta', country: 'Thailand', name: 'Ko Lanta, Thailand')
Location.create(city: 'Ko Pha Ngan', country: 'Thailand', name: 'Ko Pha Ngan, Thailand')
Location.create(city: 'Ko Phi Phi Don', country: 'Thailand', name: 'Ko Phi Phi Don, Thailand')
Location.create(city: 'Krabi Town', country: 'Thailand', name: 'Krabi Town, Thailand')
Location.create(city: 'Kruger National Park', country: 'South Africa', name: 'Kruger National Park, South Africa')
Location.create(city: 'Kuala Lumpur', country: 'Malaysia', name: 'Kuala Lumpur, Malaysia')
Location.create(city: 'La Fortuna de San Carlos', country: 'Costa Rica', name: 'La Fortuna de San Carlos, Costa Rica')
Location.create(city: 'La Jolla', country: 'United States', name: 'La Jolla, United States')
Location.create(city: 'La Romana', country: 'Dominican Republic', name: 'La Romana, Dominican Republic')
Location.create(city: 'Ladyville', country: 'Belize', name: 'Ladyville, Belize')
Location.create(city: 'Lancaster', country: 'United States', name: 'Lancaster, United States')
Location.create(city: 'Las Cruces', country: 'United States', name: 'Las Cruces, United States')
Location.create(city: 'Las Vegas', country: 'United States', name: 'Las Vegas, United States')
Location.create(city: 'Lawrenceville', country: 'United States', name: 'Lawrenceville, United States')
Location.create(city: 'Leavenworth', country: 'United States', name: 'Leavenworth, United States')
Location.create(city: 'Lecce', country: 'Italy', name: 'Lecce, Italy')
Location.create(city: 'Leticia', country: 'Colombia', name: 'Leticia, Colombia')
Location.create(city: 'Lima', country: 'Peru', name: 'Lima, Peru')
Location.create(city: 'Lincoln City', country: 'United States', name: 'Lincoln City, United States')
Location.create(city: 'Lockhart', country: 'United States', name: 'Lockhart, United States')
Location.create(city: 'London', country: 'United Kingdom', name: 'London, United Kingdom')
Location.create(city: 'Long Island City', country: 'United States', name: 'Long Island City, United States')
Location.create(city: 'Los Angeles', country: 'United States', name: 'Los Angeles, United States')
Location.create(city: 'Lowell', country: 'United States', name: 'Lowell, United States')
Location.create(city: 'Lucerne', country: 'Switzerland', name: 'Lucerne, Switzerland')
Location.create(city: 'Lyon', country: 'France', name: 'Lyon, France')
Location.create(city: 'Machu Picchu', country: 'Peru', name: 'Machu Picchu, Peru')
Location.create(city: 'Madison', country: 'United States', name: 'Madison, United States')
Location.create(city: 'Mae Rim', country: 'Thailand', name: 'Mae Rim, Thailand')
Location.create(city: 'Mae Sai', country: 'Thailand', name: 'Mae Sai, Thailand')
Location.create(city: 'Mal Pais', country: 'Costa Rica', name: 'Mal Pais, Costa Rica')
Location.create(city: 'Malaga', country: 'Spain', name: 'Malaga, Spain')
Location.create(city: 'Malibu', country: 'United States', name: 'Malibu, United States')
Location.create(city: 'Maputo', country: 'Mozambique', name: 'Maputo, Mozambique')
Location.create(city: 'Marbella', country: 'Spain', name: 'Marbella, Spain')
Location.create(city: 'Marseille', country: 'France', name: 'Marseille, France')
Location.create(city: 'Mendocino', country: 'United States', name: 'Mendocino, United States')
Location.create(city: 'Miami', country: 'United States', name: 'Miami, United States')
Location.create(city: 'Miami Beach', country: 'United States', name: 'Miami Beach, United States')
Location.create(city: 'Milan', country: 'Italy', name: 'Milan, Italy')
Location.create(city: 'Mississauga', country: 'Canada', name: 'Mississauga, Canada')
Location.create(city: 'Missoula', country: 'United States', name: 'Missoula, United States')
Location.create(city: 'Moab', country: 'United States', name: 'Moab, United States')
Location.create(city: 'Montauk', country: 'United States', name: 'Montauk, United States')
Location.create(city: 'Montego Bay', country: 'Jamaica', name: 'Montego Bay, Jamaica')
Location.create(city: 'Montepulciano', country: 'Italy', name: 'Montepulciano, Italy')
Location.create(city: 'Monterey', country: 'United States', name: 'Monterey, United States')
Location.create(city: 'Monteriggioni', country: 'Italy', name: 'Monteriggioni, Italy')
Location.create(city: 'Montezuma', country: 'Costa Rica', name: 'Montezuma, Costa Rica')
Location.create(city: 'Montreal', country: 'Canada', name: 'Montreal, Canada')
Location.create(city: 'Monument Valley', country: 'United States', name: 'Monument Valley, United States')
Location.create(city: 'Morristown', country: 'United States', name: 'Morristown, United States')
Location.create(city: 'Morro Bay', country: 'United States', name: 'Morro Bay, United States')
Location.create(city: 'Napa', country: 'United States', name: 'Napa, United States')
Location.create(city: 'Naples', country: 'United States', name: 'Naples, United States')
Location.create(city: 'Naples', country: 'Italy', name: 'Naples, Italy')
Location.create(city: 'Nardo', country: 'Italy', name: 'Nardo, Italy')
Location.create(city: 'Neah Bay', country: 'United States', name: 'Neah Bay, United States')
Location.create(city: 'Negombo', country: 'Sri Lanka', name: 'Negombo, Sri Lanka')
Location.create(city: 'Negril', country: 'Jamaica', name: 'Negril, Jamaica')
Location.create(city: 'New Hope', country: 'United States', name: 'New Hope, United States')
Location.create(city: 'New Orleans', country: 'United States', name: 'New Orleans, United States')
Location.create(city: 'New York City', country: 'United States', name: 'New York City, United States')
Location.create(city: 'Newark', country: 'United States', name: 'Newark, United States')
Location.create(city: 'Newport', country: 'United States', name: 'Newport, United States')
Location.create(city: 'Niagara Falls', country: 'United States', name: 'Niagara Falls, United States')
Location.create(city: 'Niagara Falls', country: 'Canada', name: 'Niagara Falls, Canada')
Location.create(city: 'Nice', country: 'France', name: 'Nice, France')
Location.create(city: 'North East', country: 'United States', name: 'North East, United States')
Location.create(city: 'Nosara', country: 'Costa Rica', name: 'Nosara, Costa Rica')
Location.create(city: 'Ocho Rios', country: 'Jamaica', name: 'Ocho Rios, Jamaica')
Location.create(city: 'Ojai', country: 'United States', name: 'Ojai, United States')
Location.create(city: 'Ojo Caliente', country: 'United States', name: 'Ojo Caliente, United States')
Location.create(city: 'Olympic National Park', country: 'United States', name: 'Olympic National Park, United States')
Location.create(city: 'Orlando', country: 'United States', name: 'Orlando, United States')
Location.create(city: 'Orvieto', country: 'Italy', name: 'Orvieto, Italy')
Location.create(city: 'Otranto', country: 'Italy', name: 'Otranto, Italy')
Location.create(city: 'Oudomxay', country: 'Laos', name: 'Oudomxay, Laos')
Location.create(city: 'Page', country: 'United States', name: 'Page, United States')
Location.create(city: 'Pai', country: 'Thailand', name: 'Pai, Thailand')
Location.create(city: 'Pakse', country: 'Laos', name: 'Pakse, Laos')
Location.create(city: 'Palm Coast', country: 'United States', name: 'Palm Coast, United States')
Location.create(city: 'Palm Springs', country: 'United States', name: 'Palm Springs, United States')
Location.create(city: 'Paris', country: 'France', name: 'Paris, France')
Location.create(city: 'Pattaya', country: 'Thailand', name: 'Pattaya, Thailand')
Location.create(city: 'Penang Island', country: 'Malaysia', name: 'Penang Island, Malaysia')
Location.create(city: 'Pescoluse', country: 'Italy', name: 'Pescoluse, Italy')
Location.create(city: 'Philadelphia', country: 'United States', name: 'Philadelphia, United States')
Location.create(city: 'Phnom Penh', country: 'Cambodia', name: 'Phnom Penh, Cambodia')
Location.create(city: 'Phoenicia', country: 'United States', name: 'Phoenicia, United States')
Location.create(city: 'Phoenix', country: 'United States', name: 'Phoenix, United States')
Location.create(city: 'Phong Nha-Ke Bang National Park', country: 'Vietnam', name: 'Phong Nha-Ke Bang National Park, Vietnam')
Location.create(city: 'Phonsavan', country: 'Laos', name: 'Phonsavan, Laos')
Location.create(city: 'Pisa', country: 'Italy', name: 'Pisa, Italy')
Location.create(city: 'Pismo Beach', country: 'United States', name: 'Pismo Beach, United States')
Location.create(city: 'Placencia', country: 'Belize', name: 'Placencia, Belize')
Location.create(city: 'Playa Hermosa', country: 'Costa Rica', name: 'Playa Hermosa, Costa Rica')
Location.create(city: 'Playa Samara', country: 'Costa Rica', name: 'Playa Samara, Costa Rica')
Location.create(city: 'Playa del Carmen', country: 'Mexico', name: 'Playa del Carmen, Mexico')
Location.create(city: 'Point Pleasant Beach', country: 'United States', name: 'Point Pleasant Beach, United States')
Location.create(city: 'Pompeii', country: 'Italy', name: 'Pompeii, Italy')
Location.create(city: 'Port Angeles', country: 'United States', name: 'Port Angeles, United States')
Location.create(city: 'Portland', country: 'United States', name: 'Portland, United States')
Location.create(city: 'Portland', country: 'United States', name: 'Portland, United States')
Location.create(city: 'Providenciales', country: 'Turks & Caicos', name: 'Providenciales, Turks & Caicos')
Location.create(city: 'Provincetown', country: 'United States', name: 'Provincetown, United States')
Location.create(city: 'Puerto Maldonado', country: 'Peru', name: 'Puerto Maldonado, Peru')
Location.create(city: 'Puerto Morelos', country: 'Mexico', name: 'Puerto Morelos, Mexico')
Location.create(city: 'Puerto Plata', country: 'Dominican Republic', name: 'Puerto Plata, Dominican Republic')
Location.create(city: 'Punta Cana', country: 'Dominican Republic', name: 'Punta Cana, Dominican Republic')
Location.create(city: 'Quinault', country: 'United States', name: 'Quinault, United States')
Location.create(city: 'Rapid City', country: 'United States', name: 'Rapid City, United States')
Location.create(city: 'Redding', country: 'United States', name: 'Redding, United States')
Location.create(city: 'Redwood City', country: 'United States', name: 'Redwood City, United States')
Location.create(city: 'Redwood National Park', country: 'United States', name: 'Redwood National Park, United States')
Location.create(city: 'Reedpoint', country: 'United States', name: 'Reedpoint, United States')
Location.create(city: 'Rehoboth Beach', country: 'United States', name: 'Rehoboth Beach, United States')
Location.create(city: 'Reno', country: 'United States', name: 'Reno, United States')
Location.create(city: 'Reykjavik', country: 'Iceland', name: 'Reykjavik, Iceland')
Location.create(city: 'Richland', country: 'United States', name: 'Richland, United States')
Location.create(city: 'Richmond', country: 'United States', name: 'Richmond, United States')
Location.create(city: 'Rincon', country: 'United States', name: 'Rincon, United States')
Location.create(city: 'Rome', country: 'Italy', name: 'Rome, Italy')
Location.create(city: 'Ronda', country: 'Spain', name: 'Ronda, Spain')
Location.create(city: 'Rose Hall', country: 'Jamaica', name: 'Rose Hall, Jamaica')
Location.create(city: 'Sacramento', country: 'United States', name: 'Sacramento, United States')
Location.create(city: 'Saint Augustine Beach', country: 'United States', name: 'Saint Augustine Beach, United States')
Location.create(city: 'San Diego', country: 'United States', name: 'San Diego, United States')
Location.create(city: 'San Jose', country: 'Costa Rica', name: 'San Jose, Costa Rica')
Location.create(city: 'San Juan', country: 'United States', name: 'San Juan, United States')
Location.create(city: 'San Pedro', country: 'Belize', name: 'San Pedro, Belize')
Location.create(city: 'San Pedro La Laguna', country: 'Guatemala', name: 'San Pedro La Laguna, Guatemala')
Location.create(city: 'San Simeon', country: 'United States', name: 'San Simeon, United States')
Location.create(city: 'Santa Barbara', country: 'United States', name: 'Santa Barbara, United States')
Location.create(city: 'Santa Fe', country: 'United States', name: 'Santa Fe, United States')
Location.create(city: 'Santa Maria al Bagno', country: 'Italy', name: 'Santa Maria al Bagno, Italy')
Location.create(city: 'Santa Marta', country: 'Colombia', name: 'Santa Marta, Colombia')
Location.create(city: 'Santa Monica', country: 'United States', name: 'Santa Monica, United States')
Location.create(city: 'Santa Teresa', country: 'Costa Rica', name: 'Santa Teresa, Costa Rica')
Location.create(city: 'Santo Domingo', country: 'Dominican Republic', name: 'Santo Domingo, Dominican Republic')
Location.create(city: 'Sapa', country: 'Vietnam', name: 'Sapa, Vietnam')
Location.create(city: 'Sausalito', country: 'United States', name: 'Sausalito, United States')
Location.create(city: 'Savannah', country: 'United States', name: 'Savannah, United States')
Location.create(city: 'Scottsdale', country: 'United States', name: 'Scottsdale, United States')
Location.create(city: 'Seaside Heights', country: 'United States', name: 'Seaside Heights, United States')
Location.create(city: 'Seattle', country: 'United States', name: 'Seattle, United States')
Location.create(city: 'Secaucus', country: 'United States', name: 'Secaucus, United States')
Location.create(city: 'Sedona', country: 'United States', name: 'Sedona, United States')
Location.create(city: 'Sequim', country: 'United States', name: 'Sequim, United States')
Location.create(city: 'Seward', country: 'United States', name: 'Seward, United States')
Location.create(city: 'Siem Reap', country: 'Cambodia', name: 'Siem Reap, Cambodia')
Location.create(city: 'Siena', country: 'Italy', name: 'Siena, Italy')
Location.create(city: 'Sihanoukville', country: 'Cambodia', name: 'Sihanoukville, Cambodia')
Location.create(city: 'Sioux City', country: 'United States', name: 'Sioux City, United States')
Location.create(city: 'Sitka', country: 'United States', name: 'Sitka, United States')
Location.create(city: 'Skagway', country: 'United States', name: 'Skagway, United States')
Location.create(city: 'Sonoma', country: 'United States', name: 'Sonoma, United States')
Location.create(city: 'South Lake Tahoe', country: 'United States', name: 'South Lake Tahoe, United States')
Location.create(city: 'South San Francisco', country: 'United States', name: 'South San Francisco, United States')
Location.create(city: 'Southold', country: 'United States', name: 'Southold, United States')
Location.create(city: 'Sovicille', country: 'Italy', name: 'Sovicille, Italy')
Location.create(city: 'Spokane', country: 'United States', name: 'Spokane, United States')
Location.create(city: 'Springdale', country: 'United States', name: 'Springdale, United States')
Location.create(city: 'St. Augustine', country: 'United States', name: 'St. Augustine, United States')
Location.create(city: 'St. Thomas', country: 'United States', name: 'St. Thomas, United States')
Location.create(city: 'Staten Island', country: 'United States', name: 'Staten Island, United States')
Location.create(city: 'Stellenbosch', country: 'South Africa', name: 'Stellenbosch, South Africa')
Location.create(city: 'Stowe', country: 'United States', name: 'Stowe, United States')
Location.create(city: 'Stratford', country: 'United States', name: 'Stratford, United States')
Location.create(city: 'Stresa', country: 'Italy', name: 'Stresa, Italy')
Location.create(city: 'Surat Thani', country: 'Thailand', name: 'Surat Thani, Thailand')
Location.create(city: 'Tabatinga', country: 'Brazil', name: 'Tabatinga, Brazil')
Location.create(city: 'Tachileik', country: 'Myanmar', name: 'Tachileik, Myanmar')
Location.create(city: 'Tahoe City', country: 'United States', name: 'Tahoe City, United States')
Location.create(city: 'Tannersville', country: 'United States', name: 'Tannersville, United States')
Location.create(city: 'Taos', country: 'United States', name: 'Taos, United States')
Location.create(city: 'Tempe', country: 'United States', name: 'Tempe, United States')
Location.create(city: 'Tijuana', country: 'Mexico', name: 'Tijuana, Mexico')
Location.create(city: 'Tofo', country: 'Mozambique', name: 'Tofo, Mozambique')
Location.create(city: 'Toronto', country: 'Canada', name: 'Toronto, Canada')
Location.create(city: 'Torrance', country: 'United States', name: 'Torrance, United States')
Location.create(city: 'Tortola', country: 'United Kingdom', name: 'Tortola, United Kingdom')
Location.create(city: 'Tuckerton', country: 'United States', name: 'Tuckerton, United States')
Location.create(city: 'Tulum', country: 'Mexico', name: 'Tulum, Mexico')
Location.create(city: 'Uncasville', country: 'United States', name: 'Uncasville, United States')
Location.create(city: 'Vancouver', country: 'Canada', name: 'Vancouver, Canada')
Location.create(city: 'Vatican City', country: 'Vatican City', name: 'Vatican City, Vatican City')
Location.create(city: 'Venice', country: 'Italy', name: 'Venice, Italy')
Location.create(city: 'Versailles', country: 'France', name: 'Versailles, France')
Location.create(city: 'Virginia Beach', country: 'United States', name: 'Virginia Beach, United States')
Location.create(city: 'Wading River', country: 'United States', name: 'Wading River, United States')
Location.create(city: 'Waleska', country: 'United States', name: 'Waleska, United States')
Location.create(city: 'Walla Walla', country: 'United States', name: 'Walla Walla, United States')
Location.create(city: 'Walnut Creek', country: 'United States', name: 'Walnut Creek, United States')
Location.create(city: 'Washington DC', country: 'United States', name: 'Washington DC, United States')
Location.create(city: 'Watkins Glen', country: 'United States', name: 'Watkins Glen, United States')
Location.create(city: 'West Bay', country: 'United Kingdom', name: 'West Bay, United Kingdom')
Location.create(city: 'West Hollywood', country: 'United States', name: 'West Hollywood, United States')
Location.create(city: 'West Palm Beach', country: 'United States', name: 'West Palm Beach, United States')
Location.create(city: 'West Yarmouth', country: 'United States', name: 'West Yarmouth, United States')
Location.create(city: 'White Plains', country: 'United States', name: 'White Plains, United States')
Location.create(city: 'White Sands', country: 'United States', name: 'White Sands, United States')
Location.create(city: 'Wildwood', country: 'United States', name: 'Wildwood, United States')
Location.create(city: 'Wildwood Crest', country: 'United States', name: 'Wildwood Crest, United States')
Location.create(city: 'Williams', country: 'United States', name: 'Williams, United States')
Location.create(city: 'Williamsburg', country: 'United States', name: 'Williamsburg, United States')
Location.create(city: 'Woodstock', country: 'United States', name: 'Woodstock, United States')
Location.create(city: 'Yala National Park', country: 'Sri Lanka', name: 'Yala National Park, Sri Lanka')
Location.create(city: 'Yosemite National Park', country: 'United States', name: 'Yosemite National Park, United States')
Location.create(city: 'Zion National Park', country: 'United States', name: 'Zion National Park, United States')
Location.create(city: 'Buenos Aires', country: 'Argentina', name: 'Buenos Aires, Argentina')
Location.create(city: 'Mendoza', country: 'Argentina', name: 'Mendoza, Argentina')
Location.create(city: 'Puerto Madryn', country: 'Argentina', name: 'Puerto Madryn, Argentina')
Location.create(city: 'El Calafate', country: 'Argentina', name: 'El Calafate, Argentina')
Location.create(city: 'El Chalten', country: 'Argentina', name: 'El Chalten, Argentina')
Location.create(city: 'Puerto Natales', country: 'Chile', name: 'Puerto Natales, Chile')
Location.create(city: 'Torres Del Paine', country: 'Chile', name: 'Torres Del Paine, Chile')
Location.create(city: 'Virgin Gorda', country: 'British Virgin Islands', name: 'Virgin Gorda, British Virgin Islands')
Location.create(city: 'Grand Cayman', country: 'Cayman Islands', name: 'Grand Cayman, Cayman Islands')
Location.create(city: 'Providenciales', country: 'Turks & Caicos', name: 'Providenciales, Turks & Caicos')
